### PR TITLE
Implement Nested Filters, Add Tests

### PR DESCRIPTION
**Pull request by shkfnly**
Created an implementation to allow for filters to be applied to nested data structures. All tests pass.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Hi @shkfnly, thanks for the contribution. Can you please elaborate on the motivation here? Is this something that you want Mapbox GL (native? JS?) to support? Or do you have a different use case?

**Comment by shkfnly** [comment]
The motivation is that the extra data from openstreetmap is often nested.
This means the json object from osm, has properties, which has tags nested
underneath. With the implementation you can style the osm data based on sub
categories, so if I have buildings I can symbolize only the ones tagged as
apartments. I am using it with MapboxGL and it would be cool to support it
that way. I am specifically using it for dynamic styling and more complex
filtering akin to what would be used in a desktop gis application.

Thank you for the response, I'll be around to answer any other questions.

Ashoka

**Comment by jfirebaugh** [comment]
Thanks for elaborating, and thanks for contributing. However, I think nested properties are at odds with the direction we're going for vector tiles and Mapbox GL. Supporting nested properties would not just be a change here, it would require changes in mapbox-gl-native and many other places in our stack.

As a workaround, I suggest you use a flat structure, and include openstreetmap tags directly as the `properties` of the features in your vector tiles or GeoJSON, instead of nesting them under a `tags` property.

**Comment by shkfnly** [comment]
Interesting, I didn't realize it would cause breaking changes, since the original functionality was left unchanged. 

I'll look into writing a object flattener for openstreetmap data since the properties come back nested by default. Thanks for looking into it.

**Pull request closed without merging**
