### PR TITLE
Move package to @mapbox namespace.

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by lucaswoj** [comment]
We're deprecating this package and merging it with `mapbox-gl-style-spec` 🎉

**Comment by tmcw** [comment]
👍 @lucaswoj when you deprecate in git land, please also run `npm deprecate` on it to make future npm audits aware of its deprecation! Thanks

**Comment by lucaswoj** [comment]
Done @tmcw 😄

**Comment by lucaswoj** [comment]
You can see my full deprecation checklist @ https://github.com/mapbox/mapbox-gl-style-spec/pull/639#issue-197387624. Let me know if I'm missing anything.

**Pull request closed without merging**
